import prisma from '../lib/prisma';

const turkishCities = [
  // Top Tier - Most Popular
  {
    name: 'Istanbul',
    displayName: 'Istanbul - The Historic Capital',
    region: 'Marmara',
    type: 'DESTINATION',
    description: 'Where East meets West - ancient palaces, mosques, and vibrant bazaars',
    popularityScore: 100,
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    name: 'Cappadocia',
    displayName: 'Cappadocia - Fairy Chimneys & Hot Air Balloons',
    region: 'Central Anatolia',
    type: 'DESTINATION',
    description: 'Otherworldly landscapes, cave hotels, and magical hot air balloon rides',
    popularityScore: 95,
    latitude: 38.6431,
    longitude: 34.8286,
  },
  {
    name: 'Ephesus',
    displayName: 'Ephesus - Ancient Roman City',
    region: 'Aegean',
    type: 'DESTINATION',
    description: 'Best-preserved classical city in the Mediterranean, Library of Celsus',
    popularityScore: 90,
    latitude: 37.9397,
    longitude: 27.3411,
  },
  {
    name: 'Pamukkale',
    displayName: 'Pamukkale - White Travertine Terraces',
    region: 'Aegean',
    type: 'DESTINATION',
    description: 'Stunning white calcium pools and ancient Hierapolis ruins',
    popularityScore: 85,
    latitude: 37.9204,
    longitude: 29.1210,
  },
  {
    name: 'Antalya',
    displayName: 'Antalya - Turkish Riviera',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Beautiful beaches, ancient ruins, and Mediterranean charm',
    popularityScore: 80,
    latitude: 36.8969,
    longitude: 30.7133,
  },

  // Second Tier - Popular Destinations
  {
    name: 'Bodrum',
    displayName: 'Bodrum - Aegean Paradise',
    region: 'Aegean',
    type: 'DESTINATION',
    description: 'Luxury resorts, ancient castle, and vibrant nightlife',
    popularityScore: 75,
    latitude: 37.0344,
    longitude: 27.4305,
  },
  {
    name: 'Fethiye',
    displayName: 'Fethiye - Turquoise Coast',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Ölüdeniz Blue Lagoon, paragliding, and stunning coastal scenery',
    popularityScore: 70,
    latitude: 36.6217,
    longitude: 29.1137,
  },
  {
    name: 'Kusadasi',
    displayName: 'Kusadasi - Cruise Port & Beaches',
    region: 'Aegean',
    type: 'DESTINATION',
    description: 'Gateway to Ephesus, beautiful beaches, and cruise terminal',
    popularityScore: 68,
    latitude: 37.8600,
    longitude: 27.2594,
  },
  {
    name: 'Izmir',
    displayName: 'Izmir - Modern Aegean Metropolis',
    region: 'Aegean',
    type: 'DESTINATION',
    description: 'Turkey\'s third-largest city with modern amenities and ancient Smyrna',
    popularityScore: 65,
    latitude: 38.4237,
    longitude: 27.1428,
  },
  {
    name: 'Ankara',
    displayName: 'Ankara - Turkey\'s Capital',
    region: 'Central Anatolia',
    type: 'DESTINATION',
    description: 'Modern capital city, Anıtkabir Mausoleum, museums',
    popularityScore: 60,
    latitude: 39.9334,
    longitude: 32.8597,
  },

  // Third Tier - Growing Destinations
  {
    name: 'Marmaris',
    displayName: 'Marmaris - Marina & Beaches',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Beautiful harbor, water sports, and lively atmosphere',
    popularityScore: 58,
    latitude: 36.8556,
    longitude: 28.2739,
  },
  {
    name: 'Kalkan',
    displayName: 'Kalkan - Boutique Coastal Town',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Charming hillside village with stunning Mediterranean views',
    popularityScore: 55,
    latitude: 36.2648,
    longitude: 29.4123,
  },
  {
    name: 'Kas',
    displayName: 'Kas - Diving & Nature Paradise',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Pristine waters, diving, and authentic Turkish charm',
    popularityScore: 52,
    latitude: 36.2020,
    longitude: 29.6412,
  },
  {
    name: 'Alanya',
    displayName: 'Alanya - Coastal Resort City',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Medieval castle, beautiful beaches, and all-inclusive resorts',
    popularityScore: 50,
    latitude: 36.5437,
    longitude: 31.9936,
  },
  {
    name: 'Bursa',
    displayName: 'Bursa - Green City & First Ottoman Capital',
    region: 'Marmara',
    type: 'DESTINATION',
    description: 'Historic Ottoman city, Uludağ ski resort, thermal baths',
    popularityScore: 48,
    latitude: 40.1826,
    longitude: 29.0665,
  },
  {
    name: 'Konya',
    displayName: 'Konya - City of Rumi & Whirling Dervishes',
    region: 'Central Anatolia',
    type: 'DESTINATION',
    description: 'Spiritual center, Mevlana Museum, Sufi traditions',
    popularityScore: 45,
    latitude: 37.8746,
    longitude: 32.4932,
  },
  {
    name: 'Trabzon',
    displayName: 'Trabzon - Black Sea Pearl',
    region: 'Black Sea',
    type: 'DESTINATION',
    description: 'Sumela Monastery, Uzungöl Lake, lush green landscapes',
    popularityScore: 42,
    latitude: 41.0027,
    longitude: 39.7168,
  },
  {
    name: 'Gallipoli',
    displayName: 'Gallipoli - WWI Historic Peninsula',
    region: 'Marmara',
    type: 'DESTINATION',
    description: 'WWI battlefields, ANZAC memorials, historic significance',
    popularityScore: 40,
    latitude: 40.1886,
    longitude: 26.3744,
  },
  {
    name: 'Troy',
    displayName: 'Troy - Ancient City of Legends',
    region: 'Marmara',
    type: 'DESTINATION',
    description: 'Homer\'s legendary city, ancient ruins, wooden horse replica',
    popularityScore: 38,
    latitude: 39.9577,
    longitude: 26.2388,
  },
  {
    name: 'Pergamon',
    displayName: 'Pergamon (Bergama) - Ancient Medical Center',
    region: 'Aegean',
    type: 'DESTINATION',
    description: 'Ancient Greek city, Acropolis, Asclepion healing center',
    popularityScore: 35,
    latitude: 39.1203,
    longitude: 27.1804,
  },

  // Regional Centers
  {
    name: 'Side',
    displayName: 'Side - Ancient Harbor Town',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Ancient theater, temple ruins, beautiful beaches',
    popularityScore: 33,
    latitude: 36.7673,
    longitude: 31.3905,
  },
  {
    name: 'Belek',
    displayName: 'Belek - Golf & Luxury Resorts',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'World-class golf courses, luxury all-inclusive resorts',
    popularityScore: 30,
    latitude: 36.8622,
    longitude: 31.0559,
  },
  {
    name: 'Çanakkale',
    displayName: 'Çanakkale - Gateway to Gallipoli',
    region: 'Marmara',
    type: 'DESTINATION',
    description: 'Historic Dardanelles strait, ferry to Gallipoli',
    popularityScore: 28,
    latitude: 40.1553,
    longitude: 26.4142,
  },
  {
    name: 'Göreme',
    displayName: 'Göreme - Heart of Cappadocia',
    region: 'Central Anatolia',
    type: 'DESTINATION',
    description: 'Open-air museum, cave dwellings, balloon launch site',
    popularityScore: 85,
    latitude: 38.6425,
    longitude: 34.8268,
  },
  {
    name: 'Ölüdeniz',
    displayName: 'Ölüdeniz - Blue Lagoon Paradise',
    region: 'Mediterranean',
    type: 'DESTINATION',
    description: 'Stunning blue lagoon, paragliding capital of Turkey',
    popularityScore: 65,
    latitude: 36.5490,
    longitude: 29.1170,
  },

  // Major Airports
  {
    name: 'Istanbul Airport',
    displayName: 'Istanbul Airport (IST)',
    region: 'Marmara',
    type: 'AIRPORT',
    description: 'Main international hub in Istanbul',
    popularityScore: 100,
    latitude: 41.2619,
    longitude: 28.7419,
  },
  {
    name: 'Sabiha Gökçen Airport',
    displayName: 'Sabiha Gökçen Airport (SAW)',
    region: 'Marmara',
    type: 'AIRPORT',
    description: 'Istanbul\'s second international airport',
    popularityScore: 90,
    latitude: 40.8986,
    longitude: 29.3092,
  },
  {
    name: 'Antalya Airport',
    displayName: 'Antalya Airport (AYT)',
    region: 'Mediterranean',
    type: 'AIRPORT',
    description: 'Gateway to Turkish Riviera',
    popularityScore: 85,
    latitude: 36.8987,
    longitude: 30.8005,
  },
  {
    name: 'Izmir Airport',
    displayName: 'Adnan Menderes Airport (ADB) - Izmir',
    region: 'Aegean',
    type: 'AIRPORT',
    description: 'Main airport for Aegean region',
    popularityScore: 70,
    latitude: 38.2924,
    longitude: 27.1570,
  },
  {
    name: 'Bodrum Airport',
    displayName: 'Milas-Bodrum Airport (BJV)',
    region: 'Aegean',
    type: 'AIRPORT',
    description: 'Airport serving Bodrum and surrounding areas',
    popularityScore: 65,
    latitude: 37.2506,
    longitude: 27.6643,
  },
  {
    name: 'Dalaman Airport',
    displayName: 'Dalaman Airport (DLM)',
    region: 'Mediterranean',
    type: 'AIRPORT',
    description: 'Gateway to Fethiye, Marmaris, and coastal resorts',
    popularityScore: 60,
    latitude: 36.7131,
    longitude: 28.7925,
  },
  {
    name: 'Kayseri Airport',
    displayName: 'Kayseri Erkilet Airport (ASR)',
    region: 'Central Anatolia',
    type: 'AIRPORT',
    description: 'Closest airport to Cappadocia',
    popularityScore: 75,
    latitude: 38.7704,
    longitude: 35.4954,
  },
  {
    name: 'Nevşehir Airport',
    displayName: 'Nevşehir Kapadokya Airport (NAV)',
    region: 'Central Anatolia',
    type: 'AIRPORT',
    description: 'Small airport near Cappadocia',
    popularityScore: 65,
    latitude: 38.7719,
    longitude: 34.5345,
  },
];

async function main() {
  console.log('🌍 Seeding Turkish cities...');

  for (const city of turkishCities) {
    await prisma.turkishCity.upsert({
      where: { name: city.name },
      update: city,
      create: city,
    });
    console.log(`✅ ${city.displayName}`);
  }

  console.log(`\n✨ Successfully seeded ${turkishCities.length} Turkish cities!`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding cities:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
