#!/bin/bash

# Simple test script for blog generation
# Usage: bash scripts/test-blog-generation.sh

echo "=== Blog Generation Test ==="
echo ""
echo "This script will help you test blog post generation."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Open your browser and go to:"
echo "   https://dreamdestinationturkey.com/admin/login"
echo ""
echo "2. Login with your admin credentials"
echo ""
echo "3. Go to:"
echo "   https://dreamdestinationturkey.com/admin/blog"
echo ""
echo "4. Click the 'Generate AI Post' button"
echo ""
echo "5. Wait 10-20 seconds for the AI to generate the post"
echo ""
echo "6. Check the blog posts list - you should see a new post!"
echo ""
echo "7. Visit the public blog to see it:"
echo "   https://dreamdestinationturkey.com/blog"
echo ""
echo "=== Manual Generation (6 posts - one for each category) ==="
echo ""
echo "To create one post for each category, click 'Generate AI Post' 6 times:"
echo "  - Each click creates a different category (rotates automatically)"
echo "  - Wait 10 seconds between each click"
echo "  - After 6 posts, all categories will have content"
echo ""
echo "Categories:"
echo "  1. Travel Tips"
echo "  2. Destinations"
echo "  3. Culture"
echo "  4. Food"
echo "  5. History"
echo "  6. Activities"
echo ""
